### ISSUE TITLE
Notebookでの実行フローの完成

### ISSUE THREAD

**Issue by fuyu-quant** [auto-res/researchchain#30]
notebookの最新のものは以下のリンクになります．
SemanticScholarRetrieverの挙動などいくつかの機能が改善されています．
https://github.com/auto-res/researchchain/blob/develop/examples/researchchain_demo.ipynb

**Comment by Ribosome-2021** [comment]
"optimizer"ベースで各コンポーネントを連続した実行結果
- GithubRetriever
　→コードミスによりgithub_fileに関して一部のコードしか取得できない→修正中

- CodeExtractor
　→実行可能、GithubRetrieverから正しくデータが連携される前提で、出力としても正しいものが出力されている

- Decomposer
　→実行可能、ただしプロンプトの修正必須→Aで性能向上に寄与できる部分が取得されていない、A,B同じものが出力されることがある

- Creator
　→実行可能、ただしプロンプトの修正必須→ Decomposerからの出力結果にもよるが結合はされるが実行可能なものが出力されているか微妙。。


そのほかの課題
・全体的にmemoryに入れるデータが多くなりすぎており、colabでCPUで動かすと重い。。print文で見ようものならフリーズ。。
・今回検証したgithubはいいが、今後github内のデータが大量なものを処理する際にCodeExtractorでトークンエラーになりそう
　基本的にgithubの全てのコードをLLMに投げてその中から最も重要なClassを取得するようにしているため、コード分量がありすぎるとエラーになる
・全体的にさらにプロンプトのブラッシュアップが必要(今回は除外したが前まで出していたTHINKを出させてもいいかも)
